###
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    repo: thomaslacaze/dockerhub-description
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag

- name: publish readme
  image: thomaslacaze/dockerhub-description
  settings:
    DOCKERHUB_REPOSITORY: thomaslacaze/dockerhub-description
    DOCKERHUB_USERNAME:
      from_secret: docker_username
    DOCKERHUB_PASSWORD:
      from_secret: docker_password
    README_FILEPATH: README.md
  when:
    branch:
    - master
    - main
###